"""Generates and locates the Postgres + LiteLLM proxy compose stack."""

from __future__ import annotations

import secrets
from dataclasses import dataclass
from pathlib import Path

from dgx_hub.config import user_config_dir
from dgx_hub.plugins.base import ContainerHandle, RuntimeKind

COMPOSE_PROJECT = "dgx-hub-gateway"

_CONFIG_YAML = """\
# Generated by `dgx-hub gateway start` on first run only -- edit freely,
# it is never overwritten. The model_list below is managed at runtime via
# LiteLLM's /model/new and /model/delete admin endpoints, not this file.
model_list: []
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: os.environ/DATABASE_URL
litellm_settings:
  drop_params: true
"""


@dataclass(frozen=True)
class GatewayPaths:
    dir: Path
    compose_file: Path
    config_file: Path
    env_file: Path


def gateway_paths() -> GatewayPaths:
    directory = user_config_dir() / "gateway"
    return GatewayPaths(
        dir=directory,
        compose_file=directory / "docker-compose.yaml",
        config_file=directory / "litellm-config.yaml",
        env_file=directory / ".env",
    )


def read_env_file(env_file: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not env_file.is_file():
        return values
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key] = value
    return values


def _compose_yaml(paths: GatewayPaths) -> str:
    return f"""\
# Generated by `dgx-hub gateway start` -- safe to delete, it's regenerated
# on every start. Secrets live in .env next to this file, not here.
services:
  postgres:
    # Fully qualified (not the short "postgres:16-alpine") -- podman's
    # short-name resolution can't prompt for a registry in a non-interactive
    # session and silently hangs `up` instead of erring.
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD}}
      POSTGRES_DB: litellm
    # No published port -- reachable only from litellm, by service name, on
    # dgx-hub-net. Nothing outside the gateway's own containers needs it.
    networks:
      - dgx-hub-net
    volumes:
      - dgx-hub-gateway-postgres:/var/lib/postgresql/data

  litellm:
    # The `-database` image variant runs its own Prisma migrations against
    # DATABASE_URL on boot, so no manual `prisma migrate deploy` step is
    # needed for virtual-key/spend-tracking tables to exist.
    image: ghcr.io/berriai/litellm-database:main-stable
    restart: unless-stopped
    # dgx-hub-net (not network_mode: host) so this container is reachable
    # from the real host under rootless Docker too -- host networking there
    # shares RootlessKit's private namespace, not the actual host, and
    # Docker discards `ports:` outright whenever network_mode: host is set,
    # so the two can't be combined. Model backends join this same network
    # (see launch/docker_run.py) so litellm can still reach them by
    # container name/gateway_address, regardless of which Docker flavor is
    # running underneath.
    networks:
      - dgx-hub-net
    ports:
      - "${{LITELLM_HOST}}:${{LITELLM_PORT}}:${{LITELLM_PORT}}"
    environment:
      LITELLM_MASTER_KEY: ${{LITELLM_MASTER_KEY}}
      DATABASE_URL: postgresql://litellm:${{POSTGRES_PASSWORD}}@postgres:5432/litellm
      # Required for the /model/new and /model/delete admin endpoints the
      # reconciler drives -- without it they 500 rather than persisting to
      # the DB-backed model list.
      STORE_MODEL_IN_DB: "True"
    volumes:
      # ":z" relabels the bind mount for SELinux-enforcing hosts (Fedora and
      # friends) -- without it, the container gets a silent permission
      # denial that litellm reports as "config file not found".
      - {paths.config_file}:/app/config.yaml:ro,z
    command: [
      "--config", "/app/config.yaml",
      "--port", "${{LITELLM_PORT}}",
      "--host", "${{LITELLM_HOST}}",
    ]
    depends_on:
      - postgres

networks:
  # Pre-created by `docker_adapter.ensure_network()` before `docker compose
  # up` runs (gateway/lifecycle.py) -- external because model-backend
  # containers, started independently by `dgx-hub start`, join the exact
  # same network (see launch/docker_run.py) and must resolve to it too.
  dgx-hub-net:
    external: true

volumes:
  dgx-hub-gateway-postgres:
"""


def ensure_gateway_files(litellm_port: int, host: str) -> GatewayPaths:
    """Write the compose file (always, latest port/host) and .env (secrets
    persisted across calls, generated once). The litellm config file is
    written only if missing, so hand edits to it survive restarts.
    """
    paths = gateway_paths()
    paths.dir.mkdir(parents=True, exist_ok=True)

    existing = read_env_file(paths.env_file)
    master_key = existing.get("LITELLM_MASTER_KEY") or f"sk-{secrets.token_urlsafe(32)}"
    postgres_password = existing.get("POSTGRES_PASSWORD") or secrets.token_urlsafe(24)

    paths.env_file.write_text(
        f"LITELLM_MASTER_KEY={master_key}\n"
        f"POSTGRES_PASSWORD={postgres_password}\n"
        f"LITELLM_PORT={litellm_port}\n"
        f"LITELLM_HOST={host}\n"
    )
    paths.env_file.chmod(0o600)

    paths.compose_file.write_text(_compose_yaml(paths))

    if not paths.config_file.is_file():
        paths.config_file.write_text(_CONFIG_YAML)

    return paths


def postgres_handle(paths: GatewayPaths) -> ContainerHandle:
    return ContainerHandle(
        kind=RuntimeKind.DOCKER_COMPOSE,
        compose_project=COMPOSE_PROJECT,
        compose_file=paths.compose_file,
        service_name="postgres",
    )


def litellm_handle(paths: GatewayPaths) -> ContainerHandle:
    return ContainerHandle(
        kind=RuntimeKind.DOCKER_COMPOSE,
        compose_project=COMPOSE_PROJECT,
        compose_file=paths.compose_file,
        service_name="litellm",
    )
